//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelPersona
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasBancos
    {
        public int idCuentas { get; set; }
        public int idPersona { get; set; }
        public string Banco { get; set; }
        public string Cuenta { get; set; }
    }
}
